### ISSUE TITLE
事件系统1w次收发事件，产生大量GC

### ISSUE THREAD

**Issue by gsm958708323** [tang-xiaolong/SimpleGameFramework#1]
![Snipaste_2024-05-04_14-51-29](https://github.com/tang-xiaolong/SimpleGameFramework/assets/29498846/4ee3a1fa-0d9b-4ef4-a107-9be0008734bd)
![Snipaste_2024-05-04_14-52-15](https://github.com/tang-xiaolong/SimpleGameFramework/assets/29498846/4f3c5b6b-4343-4d6d-8611-7cb7bd71b772)
![image](https://github.com/tang-xiaolong/SimpleGameFramework/assets/29498846/a3e5852f-60e3-4027-ad59-093beb50e9fb)

**Comment by tang-xiaolong** [comment]
不好意思才注意到你发的这个，我已通过这个提交修复了这个问题： https://github.com/tang-xiaolong/SimpleGameFramework/commit/ad33f7f44fbbc12b21c2627f2eb4c22f8b2ece79
这是我测试的结果，因为1W次耗费的时间较少，我将示例中的次数改成了10W次
![image](https://github.com/user-attachments/assets/1d0db2c1-0fb0-4df6-9211-1e7e49a97d8d)
![image](https://github.com/user-attachments/assets/fc8202ce-1589-4052-989a-9246e36b0f34)
